// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreatePayload struct {
	ID int `json:"id"`
}

type Error struct {
	Message string `json:"message"`
}

type TaskCompleteInput struct {
	ID int `json:"id"`
}

type TaskCreateInput struct {
	Title       string `json:"title"`
	Description string `json:"description"`
}

type TaskReopenInput struct {
	ID int `json:"id"`
}

type TaskUpdateInput struct {
	ID          int    `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
}
